server:
  servlet:
    context-path: /

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: payment-service-route
          uri: http://localhost:9090
          predicates:
            - Path=/payment-service/v3/api-docs
            - Method=GET

        - id: order-service-route
          uri: http://localhost:9095
          predicates:
            - Path=/order-service/v3/api-docs
            - Method=GET

#      routes:
#        - id: payment
#          predicates:
#            - Path=/payment/**
#          uri: http://localhost:9090
#        - id: order
#          predicates:
#            - Path=/order/**
#          uri: http://localhost:9095
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /payment-service/v3/api-docs
        name: Payment Service
      - url: /order-service/v3/api-docs
        name: Order Service
