server:
  port: 9095

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      url: http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

